DROP TABLE KIMDOHYUN_ASJC_EID CASCADE CONSTRAINTS PURGE;
CREATE TABLE KIMDOHYUN_ASJC_EID as 
	SELECT DISTINCT eid FROM SCOPUS_CLASSIFICATION_ASJC WHERE asjc_code = '2500';

CREATE INDEX KDHASJC_IDX_EID ON KIMDOHYUN_ASJC_EID (
	"EID" 
);

DROP TABLE KIMDOHYUN_TARGET_DOUCMENT CASCADE CONSTRAINTS PURGE;
CREATE TABLE KIMDOHYUN_TARGET_DOUCMENT as
SELECT eid, publication_year, source_id   
FROM SCOPUS_DOCUMENT
WHERE PUBLICATION_YEAR = '2000';


DROP TABLE KIMDOHYUN_TARGET_RESULT CASCADE CONSTRAINTS PURGE;
CREATE TABLE KIMDOHYUN_TARGET_RESULT as
SELECT /*+ use_nl(aeid) use_nl(td)*/
	td.eid, publication_year, source_id  
FROM KIMDOHYUN_ASJC_EID aeid, KIMDOHYUN_TARGET_DOUCMENT td
WHERE aeid.eid = td.eid;

COMMIT;


DROP TABLE KIMDOHYUN_DOCUMENT CASCADE CONSTRAINTS PURGE;
CREATE TABLE KIMDOHYUN_DOCUMENT as
SELECT /*+ use_nl(sd) use_nl(si) */ sd.eid, publication_year, sd.source_id   
FROM KIMDOHYUN_TARGET_RESULT sd, SCOPUS_SOURCE_INFO si
WHERE sd.source_id = si.SOURCE_ID 
AND SOURCE_TYPE = 'Journal';

COMMIT;

DROP INDEX KDH_IDX_EID ON KIMDOHYUN_DOCUMENT;
CREATE INDEX KDH_IDX_EID ON KIMDOHYUN_DOCUMENT (
	"EID" 
);

DROP INDEX KDH_IDX_SID ON KIMDOHYUN_DOCUMENT;
CREATE INDEX KDH_IDX_SID ON KIMDOHYUN_DOCUMENT (
	"SOURCE_ID" 
);

DROP INDEX KDH_IDX_YEAR ON KIMDOHYUN_DOCUMENT;
CREATE INDEX KDH_IDX_YEAR ON KIMDOHYUN_DOCUMENT (
	"PUBLICATION_YEAR" 
);

commit;

DROP TABLE KIMDOHYUN_CIT_DOCUINFO CASCADE CONSTRAINTS PURGE;
CREATE TABLE KIMDOHYUN_CIT_DOCUINFO as
	SELECT /*+ use_nl(d) use_nl(c) */
		d.eid AS eid , d.publication_year AS year, d.source_id AS jounal_id,
		c.CIT_EID
	FROM KIMDOHYUN_DOCUMENT d, SCOPUS_CITATION c 
	WHERE d.eid = c.eid;

DROP TABLE KIMDOHYUN_RESULT CASCADE CONSTRAINTS PURGE;
CREATE TABLE KIMDOHYUN_RESULT as
SELECT /*+ use_nl(d) use_nl(sd) */
	d.eid AS eid , d.year AS year, d.jounal_id AS jounal_id, d.cit_eid AS cit_eid, 
	sd.publication_year AS cit_year, sd.SOURCE_ID AS cit_jounal_id
FROM KIMDOHYUN_CIT_DOCUINFO d, SCOPUS_DOCUMENT sd 
WHERE d.cit_eid = sd.eid;


