/*생성된 Build테이블 이름을 교체하고 제약조건 및 인덱스를 생성합니다.*/

-- SCOPUS_DOCUMENT

ALTER TABLE B_SCOPUS_DOCUMENT DROP CONSTRAINT SPKSCOPUS_DOCUMENT;
ALTER TABLE B_SCOPUS_DOCUMENT ADD CONSTRAINT SPKSCOPUS_DOCUMENT PRIMARY KEY (eid);

ALTER TABLE B_SCOPUS_DOCUMENT DROP CONSTRAINT SFKSD_CT;
ALTER TABLE B_SCOPUS_DOCUMENT ADD CONSTRAINT SFKSD_CT FOREIGN KEY (citation_type) 
			REFERENCES SCOPUS_CITATION_TYPE(citation_type) ON DELETE SET NULL;
			

			
ALTER INDEX SIDX_SDEID RENAME TO OSIDX_SDEID;
DROP INDEX SIDX_SDEID;
CREATE INDEX SIDX_SDEID ON B_SCOPUS_DOCUMENT (
	"EID"
);

ALTER INDEX SIDX_SDPYEAR RENAME TO OSIDX_SDPYEAR;
DROP INDEX SIDX_SDPYEAR;
CREATE INDEX SIDX_SDPYEAR ON B_SCOPUS_DOCUMENT (
	"PUBLICATION_YEAR"
);

ALTER INDEX SIDX_SDSID RENAME TO OSIDX_SDSID;
DROP INDEX SIDX_SDSID;
CREATE INDEX SIDX_SDSID ON B_SCOPUS_DOCUMENT (
	"SOURCE_ID"
);

ALTER INDEX SIDX_SDRC RENAME TO OSIDX_SDRC;
DROP INDEX SIDX_SDRC;
CREATE INDEX SIDX_SDRC ON B_SCOPUS_DOCUMENT (
	"REF_COUNT"
);

ALTER INDEX SIDX_SDCC RENAME TO OSIDX_SDCC;
DROP INDEX SIDX_SDCC;
CREATE INDEX SIDX_SDCC ON B_SCOPUS_DOCUMENT (
	"CIT_COUNT"
);

ALTER INDEX SIDX_SDCT RENAME TO OSIDX_SDCT;
DROP INDEX SIDX_SDCT;
CREATE INDEX SIDX_SDCT ON B_SCOPUS_DOCUMENT (
	"CITATION_TYPE"
);

DROP TABLE OLD_SCOPUS_DOCUMENT CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_DOCUMENT rename to OLD_SCOPUS_DOCUMENT;
ALTER TABLE B_SCOPUS_DOCUMENT rename to SCOPUS_DOCUMENT;
commit;


-- SCOPUS_DOCUMENT_STATUS
ALTER TABLE B_SCOPUS_DOCUMENT_STATUS DROP CONSTRAINT SPKSCOPUS_DOCUMENT_STATUS;
ALTER TABLE B_SCOPUS_DOCUMENT_STATUS ADD CONSTRAINT SPKSCOPUS_DOCUMENT_STATUS PRIMARY KEY (eid);

ALTER INDEX SIDX_SDSSTATE RENAME TO OSIDX_SDSSTATE;
DROP INDEX SIDX_SDSSTATE;
CREATE INDEX SIDC_SDSSTATE ON B_SCOPUS_DOCUMENT_STATUS (
	"STATE"
);
DROP TABLE OLD_SCOPUS_DOCUMENT_STATUS CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_DOCUMENT_STATUS rename to OLD_SCOPUS_DOCUMENT_STATUS;
ALTER TABLE B_SCOPUS_DOCUMENT_STATUS rename to SCOPUS_DOCUMENT_STATUS;
commit;

-- SCOPUS_AUTHOR_KEYWORD
ALTER TABLE B_SCOPUS_AUTHOR_KEYWORD DROP CONSTRAINT SCOPUS_AUTHOR_KEYWORD;
ALTER TABLE B_SCOPUS_AUTHOR_KEYWORD ADD CONSTRAINT SCOPUS_AUTHOR_KEYWORD PRIMARY KEY (AUTHOR_KEYWORD_SEQ);

ALTER TABLE B_SCOPUS_AUTHOR_KEYWORD DROP CONSTRAINT SFKSAK_EID;
ALTER TABLE B_SCOPUS_AUTHOR_KEYWORD ADD CONSTRAINT SFKSAK_EID FOREIGN KEY (eid) 
			REFERENCES SCOPUS_DOCUMENT(eid) ON DELETE SET NULL;

ALTER INDEX SIDX_SAKEID RENAME TO OSIDX_SAKEID;
DROP INDEX SIDX_SAKEID;
CREATE INDEX SIDX_SAKEID ON B_SCOPUS_AUTHOR_KEYWORD (
	"EID"
);
ALTER INDEX SIDX_SAKKEY RENAME TO OSIDX_SAKKEY;
DROP INDEX SIDX_SAKKEY;
CREATE INDEX SIDX_SAKKEY ON B_SCOPUS_AUTHOR_KEYWORD (
	"KEYWORD"
);
ALTER INDEX SIDX_SAKAKSEQ RENAME TO OSIDX_SAKAKSEQ;
DROP INDEX SIDX_SAKAKSEQ;
CREATE INDEX SIDX_SAKAKSEQ ON B_SCOPUS_AUTHOR_KEYWORD (
	"AUTHOR_KEYWORD_SEQ"
);
DROP TABLE OLD_SCOPUS_AUTHOR_KEYWORD CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_AUTHOR_KEYWORD rename to OLD_SCOPUS_AUTHOR_KEYWORD;
ALTER TABLE B_SCOPUS_AUTHOR_KEYWORD rename to SCOPUS_AUTHOR_KEYWORD;
commit;
-- SCOPUS_INDEX_KEYWORD
/*
ALTER TABLE SCOPUS_INDEX_KEYWORD DROP CONSTRAINT SPKSCOPUS_INDEX_KEYWORD;
ALTER TABLE SCOPUS_INDEX_KEYWORD ADD CONSTRAINT SPKSCOPUS_INDEX_KEYWORD PRIMARY KEY (EID, KEYWORD);
*/
ALTER TABLE B_SCOPUS_INDEX_KEYWORD DROP CONSTRAINT SFKSIK_EID;
ALTER TABLE B_SCOPUS_INDEX_KEYWORD ADD CONSTRAINT SFKSIK_EID FOREIGN KEY (EID) REFERENCES SCOPUS_DOCUMENT(EID) ON DELETE SET NULL;

ALTER INDEX SIDX_SIKEID RENAME TO OSIDX_SIKEID;
DROP INDEX SIDX_SIKEID;
CREATE INDEX SIDX_SIKEID ON B_SCOPUS_INDEX_KEYWORD (
	"EID"
);
ALTER INDEX SIDX_SIKTYPE RENAME TO OSIDX_SIKTYPE;
DROP INDEX SIDX_SIKTYPE;
CREATE INDEX SIDX_SIKTYPE ON B_SCOPUS_INDEX_KEYWORD (
	"TYPE"
);
ALTER INDEX SIDX_SIKKEY RENAME TO OSIDX_SIKKEY;
DROP INDEX SIDX_SIKKEY;
CREATE INDEX SIDX_SIKKEY ON B_SCOPUS_INDEX_KEYWORD (
	"KEYWORD"
);
DROP TABLE OLD_SCOPUS_INDEX_KEYWORD CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_INDEX_KEYWORD rename to OLD_SCOPUS_INDEX_KEYWORD;
ALTER TABLE B_SCOPUS_INDEX_KEYWORD rename to SCOPUS_INDEX_KEYWORD;
commit;

-- SCOPUS_CLASSIFICATION_ASJC
ALTER TABLE B_SCOPUS_CLASSIFICATION_ASJC DROP CONSTRAINT SPKSCA;
ALTER TABLE B_SCOPUS_CLASSIFICATION_ASJC ADD CONSTRAINT SPKSCA PRIMARY KEY (eid,asjc_code);

ALTER TABLE B_SCOPUS_CLASSIFICATION_ASJC DROP CONSTRAINT SFKSCA_EID;
ALTER TABLE B_SCOPUS_CLASSIFICATION_ASJC ADD CONSTRAINT SFKSCA_EID FOREIGN KEY (eid) 
			REFERENCES SCOPUS_DOCUMENT(eid) ON DELETE SET NULL;
			
ALTER TABLE B_SCOPUS_CLASSIFICATION_ASJC DROP CONSTRAINT SFKSCA_ASJC;
ALTER TABLE B_SCOPUS_CLASSIFICATION_ASJC ADD CONSTRAINT SFKSCA_ASJC FOREIGN KEY (asjc_code) 
			REFERENCES SCOPUS_ASJC(asjc_code) ON DELETE SET NULL;
			
ALTER INDEX SIDXSCA_SCAEID RENAME TO OSIDXSCA_SCAEID;
DROP INDEX SIDXSCA_SCAEID;
CREATE INDEX SIDXSCA_SCAEID ON B_SCOPUS_CLASSIFICATION_ASJC (
	"EID"
);
ALTER INDEX SIDXSCA_SCAASJC RENAME TO OSIDXSCA_SCAASJC;
DROP INDEX SIDXSCA_SCAASJC;
CREATE INDEX SIDXSCA_SCAASJC ON B_SCOPUS_CLASSIFICATION_ASJC (
	"ASJC_CODE"
);			

DROP TABLE OLD_SCOPUS_CLASSIFICATION_ASJC CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_CLASSIFICATION_ASJC rename to OLD_SCOPUS_CLASSIFICATION_ASJC;
ALTER TABLE B_SCOPUS_CLASSIFICATION_ASJC rename to SCOPUS_CLASSIFICATION_ASJC;
commit;

-- SCOPUS_AUTHOR
ALTER TABLE B_SCOPUS_AUTHOR DROP CONSTRAINT SPKSCOPUS_AUTHOR;
ALTER TABLE B_SCOPUS_AUTHOR ADD CONSTRAINT SPKSCOPUS_AUTHOR PRIMARY KEY (author_seq);

ALTER INDEX SIDX_SASEQ RENAME TO OSIDX_SASEQ;
DROP INDEX SIDX_SASEQ;
CREATE INDEX SIDX_SASEQ ON B_SCOPUS_AUTHOR (
	"AUTHOR_SEQ"
);
ALTER INDEX SIDX_SAAI RENAME TO OSIDX_SAAI;
DROP INDEX SIDX_SAAI;
CREATE INDEX SIDX_SAAI ON B_SCOPUS_AUTHOR (
	"AUTHOR_ID"
);
ALTER INDEX SIDX_SAAN RENAME TO OSIDX_SAAN;
DROP INDEX SIDX_SAAN;
CREATE INDEX SIDX_SAAN ON B_SCOPUS_AUTHOR (
	"AUTHOR_NAME"
);
ALTER INDEX SIDX_SAEMAIL RENAME TO OSIDX_SAEMAIL;
DROP INDEX SIDX_SAEMAIL;
CREATE INDEX SIDX_SAEMAIL ON B_SCOPUS_AUTHOR (
	"EMAIL"
);
DROP TABLE OLD_SCOPUS_AUTHOR CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_AUTHOR rename to OLD_SCOPUS_AUTHOR;
ALTER TABLE B_SCOPUS_AUTHOR rename to SCOPUS_AUTHOR;
commit;

-- SCOPUS_AUTHOR_ID_INFO
ALTER TABLE B_SCOPUS_AUTHOR_ID_INFO DROP CONSTRAINT SPKSCOPUS_AUTHOR_ID_INFO;
ALTER TABLE B_SCOPUS_AUTHOR_ID_INFO ADD CONSTRAINT SPKSCOPUS_AUTHOR_ID_INFO PRIMARY KEY (eid, group_sequence, author_id);

ALTER INDEX SIDX_SAIIEID RENAME TO OSIDX_SAIIEID;
DROP INDEX SIDX_SAIIEID;
CREATE INDEX SIDX_SAIIEID ON B_SCOPUS_AUTHOR_ID_INFO (
	"EID"
);
ALTER INDEX SIDX_SAIIGS RENAME TO OSIDX_SAIIGS;
DROP INDEX SIDX_SAIIGS;
CREATE INDEX SIDX_SAIIGS ON B_SCOPUS_AUTHOR_ID_INFO (
	"GROUP_SEQUENCE"
);
ALTER INDEX SIDX_SAIIAI RENAME TO OSIDX_SAIIAI;
DROP INDEX SIDX_SAIIAI;
CREATE INDEX SIDX_SAIIAI ON B_SCOPUS_AUTHOR_ID_INFO (
	"AUTHOR_ID"
);
ALTER INDEX SIDX_SAIIAN RENAME TO OSIDX_SAIIAN;
DROP INDEX SIDX_SAIIAN;
CREATE INDEX SIDX_SAIIAN ON B_SCOPUS_AUTHOR_ID_INFO (
	"AUTHOR_NAME"
;
DROP TABLE OLD_SCOPUS_AUTHOR_ID_INFO CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_AUTHOR_ID_INFO rename to OLD_SCOPUS_AUTHOR_ID_INFO;
ALTER TABLE B_SCOPUS_AUTHOR_ID_INFO rename to SCOPUS_AUTHOR_ID_INFO;
commit;

-- SCOPUS_CORRESPOND_AUTHOR
ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR DROP CONSTRAINT SPKSCOPUS_CORRESPOND_AUTHOR;
ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR ADD CONSTRAINT SPKSCOPUS_CORRESPOND_AUTHOR PRIMARY KEY (eid);

ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR DROP CONSTRAINT SFKSCA_EID;
ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR ADD CONSTRAINT SFKSCA_EID FOREIGN KEY (eid)  REFERENCES SCOPUS_DOCUMENT(eid) ON DELETE SET NULL;
/*			
ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR DROP CONSTRAINT SFKSCA_ASEQ;
ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR ADD CONSTRAINT SFKSCA_ASEQ FOREIGN KEY (AUTHOR_SEQ) REFERENCES SCOPUS_AUTHOR(AUTHOR_SEQ) ON DELETE SET NULL;

ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR DROP CONSTRAINT SFKSCA_ACC;
ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR ADD CONSTRAINT SFKSCA_ACC FOREIGN KEY (COUNTRY_CODE) REFERENCES SCOPUS_COUNTRY_CODE(COUNTRY_CODE) ON DELETE SET NULL;
*/
ALTER INDEX SIDX_SCAEID RENAME TO OSIDX_SCAEID;
DROP INDEX SIDX_SCAEID;
CREATE INDEX SIDX_SCAEID ON B_SCOPUS_CORRESPOND_AUTHOR (
	"EID"
);
ALTER INDEX SIDX_SCASEQ RENAME TO OSIDX_SCASEQ;
DROP INDEX SIDX_SCASEQ;
CREATE INDEX SIDX_SCASEQ ON B_SCOPUS_CORRESPOND_AUTHOR (
	"AUTHOR_SEQ"
);
DROP TABLE OLD_SCOPUS_CORRESPOND_AUTHOR CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_CORRESPOND_AUTHOR rename to OLD_SCOPUS_CORRESPOND_AUTHOR;
ALTER TABLE B_SCOPUS_CORRESPOND_AUTHOR rename to SCOPUS_CORRESPOND_AUTHOR;
commit;

-- SCOPUS_CITATION
ALTER TABLE B_SCOPUS_CITATION DROP CONSTRAINT SPKSCOPUS_CITATION;
ALTER TABLE B_SCOPUS_CITATION ADD CONSTRAINT SPKSCOPUS_CITATION PRIMARY KEY (eid,cit_eid);

ALTER TABLE B_SCOPUS_CITATION DROP CONSTRAINT SFKSC_EID;
ALTER TABLE B_SCOPUS_CITATION ADD CONSTRAINT SFKSC_EID FOREIGN KEY (eid) 
			REFERENCES SCOPUS_DOCUMENT(eid) ON DELETE SET NULL;

ALTER INDEX SIDX_SCEID RENAME TO OSIDX_SCEID;
DROP INDEX SIDX_SCEID;
CREATE INDEX SIDX_SCEID ON B_SCOPUS_CITATION (
	"EID"
);
ALTER INDEX SIDX_SCCEID RENAME TO OSIDX_SCCEID;
DROP INDEX SIDX_SCCEID;
CREATE INDEX SIDX_SCCEID ON B_SCOPUS_CITATION (
	"CIT_EID"
);
DROP TABLE OLD_SCOPUS_CITATION CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_CITATION rename to OLD_SCOPUS_CITATION;
ALTER TABLE B_SCOPUS_CITATION rename to SCOPUS_CITATION;
commit;


-- SCOPUS_REFERENCE
ALTER TABLE B_SCOPUS_REFERENCE DROP CONSTRAINT SPKSCOPUS_REFERENCE;
ALTER TABLE B_SCOPUS_REFERENCE ADD CONSTRAINT SPKSCOPUS_REFERENCE PRIMARY KEY (eid,ref_eid);

ALTER TABLE B_SCOPUS_REFERENCE DROP CONSTRAINT SFKSR_EID;
ALTER TABLE B_SCOPUS_REFERENCE ADD CONSTRAINT SFKSR_EID FOREIGN KEY (eid) 
			REFERENCES SCOPUS_DOCUMENT(eid) ON DELETE SET NULL;

ALTER INDEX SIDX_SREID RENAME TO OSIDX_SREID;			
DROP INDEX SIDX_SREID;
CREATE INDEX SIDX_SREID ON B_SCOPUS_REFERENCE (
	"EID"
);
ALTER INDEX SIDX_SRREID RENAME TO OSIDX_SRREID;			
DROP INDEX SIDX_SRREID;
CREATE INDEX SIDX_SRREID ON B_SCOPUS_REFERENCE (
	"REF_EID"
);

ALTER INDEX SIDX_SRRYEAR RENAME TO OSIDX_SRRYEAR;			
DROP INDEX SIDX_SRRYEAR;
CREATE INDEX SIDX_SRRYEAR ON B_SCOPUS_REFERENCE (
	"PUBLICATION_YEAR"
);

DROP TABLE OLD_SCOPUS_REFERENCE CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_REFERENCE rename to OLD_SCOPUS_REFERENCE;
ALTER TABLE B_SCOPUS_REFERENCE rename to SCOPUS_REFERENCE;
commit;

-- SCOPUS_AFFILATION_GROUP
ALTER TABLE B_SCOPUS_AFFILATION_GROUP DROP CONSTRAINT SPKSCOPUS_AFFILATION_GROUP;
ALTER TABLE B_SCOPUS_AFFILATION_GROUP ADD CONSTRAINT SPKSCOPUS_AFFILATION_GROUP PRIMARY KEY (eid,group_sequence);

ALTER TABLE B_SCOPUS_AFFILATION_GROUP DROP CONSTRAINT SFKSAG_EID;
ALTER TABLE B_SCOPUS_AFFILATION_GROUP ADD CONSTRAINT SFKSAG_EID FOREIGN KEY (eid) 
			REFERENCES SCOPUS_DOCUMENT(eid) ON DELETE SET NULL;

/*			
ALTER TABLE B_SCOPUS_AFFILATION_GROUP DROP CONSTRAINT SFKSAG_CC;
ALTER TABLE B_SCOPUS_AFFILATION_GROUP ADD CONSTRAINT SFKSAG_CC FOREIGN KEY (COUNTRY_CODE) REFERENCES SCOPUS_COUNTRY_CODE(COUNTRY_CODE) ON DELETE SET NULL;
*/		
ALTER INDEX SIDX_SAGEID RENAME TO OSIDX_SAGEID;			
DROP INDEX SIDX_SAGEID;
CREATE INDEX SIDX_SAGEID ON B_SCOPUS_AFFILATION_GROUP (
	"EID"
);
ALTER INDEX SIDX_SAGAFID RENAME TO OSIDX_SAGAFID;			
DROP INDEX SIDX_SAGAFID;
CREATE INDEX SIDX_SAGAFID ON B_SCOPUS_AFFILATION_GROUP (
	"AFID"
);
ALTER INDEX SIDX_SAGCC RENAME TO OSIDX_SAGCC;			
DROP INDEX SIDX_SAGCC;
CREATE INDEX SIDX_SAGCC ON B_SCOPUS_AFFILATION_GROUP (
	"COUNTRY_CODE"
);
ALTER INDEX SIDX_SAGGS RENAME TO OSIDX_SAGGS;			
DROP INDEX SIDX_SAGGS;
CREATE INDEX SIDX_SAGGS ON B_SCOPUS_AFFILATION_GROUP (
	"GROUP_SEQUENCE"
);
DROP TABLE OLD_SCOPUS_AFFILATION_GROUP CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_AFFILATION_GROUP rename to OLD_SCOPUS_AFFILATION_GROUP;
ALTER TABLE B_SCOPUS_AFFILATION_GROUP rename to SCOPUS_AFFILATION_GROUP;
commit;


-- SCOPUS_AUTHOR_GROUP
ALTER TABLE B_SCOPUS_AUTHOR_GROUP DROP CONSTRAINT SPKSCOPUS_AUTHOR_GROUP;
ALTER TABLE B_SCOPUS_AUTHOR_GROUP ADD CONSTRAINT SPKSCOPUS_AUTHOR_GROUP PRIMARY KEY (EID,GROUP_SEQUENCE, AUTHOR_SEQ);

ALTER TABLE B_SCOPUS_AUTHOR_GROUP DROP CONSTRAINT SFKSAUTHORG_SEQ;
ALTER TABLE B_SCOPUS_AUTHOR_GROUP ADD CONSTRAINT SFKSAUTHORG_SEQ FOREIGN KEY (author_seq) 
			REFERENCES SCOPUS_AUTHOR(author_seq) ON DELETE SET NULL;
			
ALTER TABLE B_SCOPUS_AUTHOR_GROUP DROP CONSTRAINT SFKSAUTHORG_SEQ;
ALTER TABLE B_SCOPUS_AUTHOR_GROUP ADD CONSTRAINT SFKSAUTHORG_SEQ FOREIGN KEY (eid,group_sequence) 
			REFERENCES SCOPUS_AFFILATION_GROUP(eid,group_sequence) ON DELETE SET NULL;

ALTER INDEX SIDX_SAUTHORGEID RENAME TO OSIDX_SAUTHORGEID;			
DROP INDEX SIDX_SAUTHORGEID;
CREATE INDEX SIDX_SAUTHORGEID ON B_SCOPUS_AUTHOR_GROUP (
	"EID"
);

ALTER INDEX SIDX_SAUTHORGASEQ RENAME TO OSIDX_SAUTHORGASEQ;			
DROP INDEX SIDX_SAUTHORGASEQ;
CREATE INDEX SIDX_SAUTHORGASEQ ON B_SCOPUS_AUTHOR_GROUP (
	"AUTHOR_SEQ"
);

ALTER INDEX SIDX_SAUTHORGGSEQ RENAME TO OSIDX_SAUTHORGGSEQ;			
DROP INDEX SIDX_SAUTHORGGSEQ;
CREATE INDEX SIDX_SAUTHORGGSEQ ON B_SCOPUS_AUTHOR_GROUP (
	"GROUP_SEQUENCE"
);

DROP TABLE OLD_SCOPUS_AUTHOR_GROUP CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_AUTHOR_GROUP rename to OLD_SCOPUS_AUTHOR_GROUP;
ALTER TABLE B_SCOPUS_AUTHOR_GROUP rename to SCOPUS_AUTHOR_GROUP;
commit;


-- SCOPUS_CLASSIFICATION_OTHER
ALTER TABLE B_SCOPUS_CLASSIFICATION_OTHERS DROP CONSTRAINT SPKSCOPUS_CLASS_OTHERS;
ALTER TABLE B_SCOPUS_CLASSIFICATION_OTHERS ADD CONSTRAINT SPKSCOPUS_CLASS_OTHERS PRIMARY KEY (eid,type,code);

ALTER INDEX SIDX_SCOEID RENAME TO OSIDX_SCOEID;
DROP INDEX SIDX_SCOEID;
CREATE INDEX SIDX_SCOEID ON B_SCOPUS_CLASSIFICATION_OTHERS (
	"EID"
);
DROP TABLE OLD_SCOPUS_CLASS_OTHERS CASCADE CONSTRAINTS PURGE;
ALTER TABLE SCOPUS_CLASSIFICATION_OTHERS rename to OLD_SCOPUS_CLASS_OTHERS;
ALTER TABLE B_SCOPUS_CLASSIFICATION_OTHERS rename to SCOPUS_CLASSIFICATION_OTHERS;
commit;
exit