/**
 * 검색엔진이 사용할 색인 DB를 생성한다.
 * 저자 검색과 기관 검색이 활용된다.
 */

--저자 검색
/*
DROP TABLE SCOPUS_AUTHOR_SEARCH CASCADE CONSTRAINTS PURGE;
CREATE TABLE SCOPUS_AUTHOR_SEARCH(
	author_id  VARCHAR2(12)  NOT NULL ,
	author_name  CLOB  NULL ,
	index_name  CLOB  NULL ,
	email  CLOB  NULL,
	doc_count  VARCHAR2(10)  NULL
);
*/
--색인 속도 증가를 위해 CLOB을 varchar로 변경
--이메일은 최대 4천자까지만 지원.
DROP TABLE SCOPUS_AUTHOR_SEARCH CASCADE CONSTRAINTS PURGE;
CREATE TABLE SCOPUS_AUTHOR_SEARCH(
  AUTHOR_ID	VARCHAR(12) NOT NULL,
  AUTHOR_NAME VARCHAR(1024) ,
  INDEX_NAME VARCHAR(1024),
  EMAIL VARCHAR(4000),
  DOC_COUNT VARCHAR(10)
);
COMMIT;

CREATE INDEX SIDX_SASEARCHAUTHORID ON SCOPUS_AUTHOR_SEARCH (
	"AUTHOR_ID"
);


DROP TABLE SCOPUS_AFFILATION_SEARCH_DATA CASCADE CONSTRAINTS PURGE;
CREATE TABLE SCOPUS_AFFILATION_SEARCH_DATA as
  SELECT afid, COUNT(DISTINCT eid) AS doc_cnt FROM SCOPUS_AFFILATION_GROUP
  WHERE afid IS NOT null
  GROUP BY afid;
  
commit;  

--기관 검색
DROP TABLE SCOPUS_AFFILATION_SEARCH CASCADE CONSTRAINTS PURGE;
CREATE TABLE SCOPUS_AFFILATION_SEARCH(
	afid  VARCHAR2(12)  NOT NULL ,
	org_name  CLOB  NULL ,
	country  CLOB  NULL ,
	doc_count  VARCHAR2(10)  NOT NULL
);

CREATE INDEX SIDX_SASEARCH ON SCOPUS_AFFILATION_SEARCH (
	"AFID"
);

commit;

exit