package kr.co.tqk.web.db.dao.export;

public enum ExportField {
	TITLE, ABSTRACT, YEAR, DOI, KEYWORD, INDEX_KEYWORD, ASJC, NUMBER_CITATION, CITATION, NUMBER_REFERENCE, REFERENCE, AUTHOR_EMAIL, AUTHOR_COUNTRYCODE, AUTHOR_AUTHORINFO, AUTHOR_NAME, AFFILIATION_NAME, AFFILIATION_COUNTRY, SOURCE_SOURCETITLE, SOURCE_VOLUMN, SOURCE_ISSUE, SOURCE_PAGE, SOURCE_TYPE, SOURCE_PUBLICSHERNAME, SOURCE_COUNTRY, SOURCE_PISSN, SOURCE_EISSN, CORR_AUTHORNAME, CORR_COUNTRYCODE, CORR_EMAIL, CORR_AFFILIATION, CITATION_TYPE;
}
